oracle id = project
oracle pass = project

===================================================================

CREATE TABLE MEMBER 
(
   USERID VARCHAR2(20) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
   PASSWD VARCHAR2(20) CONSTRAINT MEMBER_PASSWD_NN NOT NULL,
   USERNAME VARCHAR2(20) CONSTRAINT MEMBER_USERNAME_NN NOT NULL,
   GRADE VARCHAR2(40) DEFAULT '일반회원',
   PHONE1 VARCHAR2(3) CONSTRAINT MEMBER_PHONE1_NN NOT NULL,
   PHONE2 VARCHAR2(4) CONSTRAINT MEMBER_PHONE2_NN NOT NULL,
   PHONE3 VARCHAR2(4) CONSTRAINT MEMBER_PHONE3_NN NOT NULL,
   EMAIL1 VARCHAR2(20) CONSTRAINT MEMBER_EMAIL1_NN NOT NULL,
   EMAIL2 VARCHAR2(15) CONSTRAINT MEMBER_EMAIL2_NN NOT NULL,
   MEMBERNO VARCHAR2(100) CONSTRAINT MEMBER_MEMBERNO_UK UNIQUE ,
   REGDATE DATE DEFAULT SYSDATE
);